# Generated by Django 4.1 on 2022-10-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.TextField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('discount', models.IntegerField()),
                ('pic', models.FileField(upload_to='products')),
                ('discountprice', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
