# Generated by Django 4.1.2 on 2022-10-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
