# Generated by Django 4.1.2 on 2022-10-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.FileField(default='koala.jpg', upload_to='hardware'),
        ),
    ]
