# Generated by Django 4.1.2 on 2022-10-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.FileField(default='koala.jpg', upload_to='Product'),
        ),
    ]
